repository: mhiro2/seedling

coverage:
  exclude:
    - "seedlingtest/**"
    - "internal/testutil/**"
    - "cmd/seedling-gen/main.go"

codeToTestRatio:
  code:
    - "**/*.go"
    - "!**/*_test.go"
    - "!integration/**"
  test:
    - "**/*_test.go"
    - "!integration/**"

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/octocov-report

comment:
  if: is_pull_request
  hideFooterLink: false

summary:
  if: is_pull_request
  hideFooterLink: false

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}/octocov-report
