// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/mhiro2/seedling/cmd/seedling-gen/testdata/gorm_actual/model"
)

func newMembership(db *gorm.DB, opts ...gen.DOOption) membership {
	_membership := membership{}

	_membership.membershipDo.UseDB(db, opts...)
	_membership.membershipDo.UseModel(&model.Membership{})

	tableName := _membership.membershipDo.TableName()
	_membership.ALL = field.NewAsterisk(tableName)
	_membership.OrganizationID = field.NewInt32(tableName, "organization_id")
	_membership.UserID = field.NewInt32(tableName, "user_id")

	_membership.fillFieldMap()

	return _membership
}

type membership struct {
	membershipDo membershipDo

	ALL            field.Asterisk
	OrganizationID field.Int32
	UserID         field.Int32

	fieldMap map[string]field.Expr
}

func (m membership) Table(newTableName string) *membership {
	m.membershipDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m membership) As(alias string) *membership {
	m.membershipDo.DO = *(m.membershipDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *membership) updateTableName(table string) *membership {
	m.ALL = field.NewAsterisk(table)
	m.OrganizationID = field.NewInt32(table, "organization_id")
	m.UserID = field.NewInt32(table, "user_id")

	m.fillFieldMap()

	return m
}

func (m *membership) WithContext(ctx context.Context) IMembershipDo {
	return m.membershipDo.WithContext(ctx)
}

func (m membership) TableName() string { return m.membershipDo.TableName() }

func (m membership) Alias() string { return m.membershipDo.Alias() }

func (m membership) Columns(cols ...field.Expr) gen.Columns { return m.membershipDo.Columns(cols...) }

func (m *membership) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *membership) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 2)
	m.fieldMap["organization_id"] = m.OrganizationID
	m.fieldMap["user_id"] = m.UserID
}

func (m membership) clone(db *gorm.DB) membership {
	m.membershipDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m membership) replaceDB(db *gorm.DB) membership {
	m.membershipDo.ReplaceDB(db)
	return m
}

type membershipDo struct{ gen.DO }

type IMembershipDo interface {
	gen.SubQuery
	Debug() IMembershipDo
	WithContext(ctx context.Context) IMembershipDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMembershipDo
	WriteDB() IMembershipDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMembershipDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMembershipDo
	Not(conds ...gen.Condition) IMembershipDo
	Or(conds ...gen.Condition) IMembershipDo
	Select(conds ...field.Expr) IMembershipDo
	Where(conds ...gen.Condition) IMembershipDo
	Order(conds ...field.Expr) IMembershipDo
	Distinct(cols ...field.Expr) IMembershipDo
	Omit(cols ...field.Expr) IMembershipDo
	Join(table schema.Tabler, on ...field.Expr) IMembershipDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMembershipDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMembershipDo
	Group(cols ...field.Expr) IMembershipDo
	Having(conds ...gen.Condition) IMembershipDo
	Limit(limit int) IMembershipDo
	Offset(offset int) IMembershipDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMembershipDo
	Unscoped() IMembershipDo
	Create(values ...*model.Membership) error
	CreateInBatches(values []*model.Membership, batchSize int) error
	Save(values ...*model.Membership) error
	First() (*model.Membership, error)
	Take() (*model.Membership, error)
	Last() (*model.Membership, error)
	Find() ([]*model.Membership, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Membership, err error)
	FindInBatches(result *[]*model.Membership, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Membership) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMembershipDo
	Assign(attrs ...field.AssignExpr) IMembershipDo
	Joins(fields ...field.RelationField) IMembershipDo
	Preload(fields ...field.RelationField) IMembershipDo
	FirstOrInit() (*model.Membership, error)
	FirstOrCreate() (*model.Membership, error)
	FindByPage(offset int, limit int) (result []*model.Membership, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMembershipDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m membershipDo) Debug() IMembershipDo {
	return m.withDO(m.DO.Debug())
}

func (m membershipDo) WithContext(ctx context.Context) IMembershipDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m membershipDo) ReadDB() IMembershipDo {
	return m.Clauses(dbresolver.Read)
}

func (m membershipDo) WriteDB() IMembershipDo {
	return m.Clauses(dbresolver.Write)
}

func (m membershipDo) Session(config *gorm.Session) IMembershipDo {
	return m.withDO(m.DO.Session(config))
}

func (m membershipDo) Clauses(conds ...clause.Expression) IMembershipDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m membershipDo) Returning(value interface{}, columns ...string) IMembershipDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m membershipDo) Not(conds ...gen.Condition) IMembershipDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m membershipDo) Or(conds ...gen.Condition) IMembershipDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m membershipDo) Select(conds ...field.Expr) IMembershipDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m membershipDo) Where(conds ...gen.Condition) IMembershipDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m membershipDo) Order(conds ...field.Expr) IMembershipDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m membershipDo) Distinct(cols ...field.Expr) IMembershipDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m membershipDo) Omit(cols ...field.Expr) IMembershipDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m membershipDo) Join(table schema.Tabler, on ...field.Expr) IMembershipDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m membershipDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMembershipDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m membershipDo) RightJoin(table schema.Tabler, on ...field.Expr) IMembershipDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m membershipDo) Group(cols ...field.Expr) IMembershipDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m membershipDo) Having(conds ...gen.Condition) IMembershipDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m membershipDo) Limit(limit int) IMembershipDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m membershipDo) Offset(offset int) IMembershipDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m membershipDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMembershipDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m membershipDo) Unscoped() IMembershipDo {
	return m.withDO(m.DO.Unscoped())
}

func (m membershipDo) Create(values ...*model.Membership) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m membershipDo) CreateInBatches(values []*model.Membership, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m membershipDo) Save(values ...*model.Membership) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m membershipDo) First() (*model.Membership, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Membership), nil
	}
}

func (m membershipDo) Take() (*model.Membership, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Membership), nil
	}
}

func (m membershipDo) Last() (*model.Membership, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Membership), nil
	}
}

func (m membershipDo) Find() ([]*model.Membership, error) {
	result, err := m.DO.Find()
	return result.([]*model.Membership), err
}

func (m membershipDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Membership, err error) {
	buf := make([]*model.Membership, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m membershipDo) FindInBatches(result *[]*model.Membership, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m membershipDo) Attrs(attrs ...field.AssignExpr) IMembershipDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m membershipDo) Assign(attrs ...field.AssignExpr) IMembershipDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m membershipDo) Joins(fields ...field.RelationField) IMembershipDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m membershipDo) Preload(fields ...field.RelationField) IMembershipDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m membershipDo) FirstOrInit() (*model.Membership, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Membership), nil
	}
}

func (m membershipDo) FirstOrCreate() (*model.Membership, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Membership), nil
	}
}

func (m membershipDo) FindByPage(offset int, limit int) (result []*model.Membership, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m membershipDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m membershipDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m membershipDo) Delete(models ...*model.Membership) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *membershipDo) withDO(do gen.Dao) *membershipDo {
	m.DO = *do.(*gen.DO)
	return m
}
