// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCountry = "countries"

// Country mapped from table <countries>
type Country struct {
	ID   *int32 `gorm:"column:id;primaryKey" json:"id"`
	Code string `gorm:"column:code;not null" json:"code"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName Country's table name
func (*Country) TableName() string {
	return TableNameCountry
}
