// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMembership = "memberships"

// Membership mapped from table <memberships>
type Membership struct {
	OrganizationID int32 `gorm:"column:organization_id;primaryKey" json:"organization_id"`
	UserID         int32 `gorm:"column:user_id;primaryKey;not null" json:"user_id"`
}

// TableName Membership's table name
func (*Membership) TableName() string {
	return TableNameMembership
}
