// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenant holds the string denoting the tenant field in the database.
	FieldTenant = "tenant"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldCompanyUUID holds the string denoting the company_uuid field in the database.
	FieldCompanyUUID = "company_uuid"
	// FieldOidcURL holds the string denoting the oidc_url field in the database.
	FieldOidcURL = "oidc_url"
	// EdgeCompany holds the string denoting the company edge name in mutations.
	EdgeCompany = "company"
	// Table holds the table name of the user in the database.
	Table = "users"
	// CompanyTable is the table that holds the company relation/edge.
	CompanyTable = "users"
	// CompanyInverseTable is the table name for the Company entity.
	// It exists in this package in order to avoid circular dependency with the "company" package.
	CompanyInverseTable = "companies"
	// CompanyColumn is the table column denoting the company relation/edge.
	CompanyColumn = "company_uuid"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldTenant,
	FieldName,
	FieldNickname,
	FieldCompanyUUID,
	FieldOidcURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenant orders the results by the tenant field.
func ByTenant(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenant, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}

// ByCompanyUUID orders the results by the company_uuid field.
func ByCompanyUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompanyUUID, opts...).ToFunc()
}

// ByOidcURL orders the results by the oidc_url field.
func ByOidcURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOidcURL, opts...).ToFunc()
}

// ByCompanyField orders the results by company field.
func ByCompanyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompanyStep(), sql.OrderByField(field, opts...))
	}
}
func newCompanyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompanyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CompanyTable, CompanyColumn),
	)
}
