// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mhiro2/seedling/cmd/seedling-gen/testdata/ent_actual/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Tenant applies equality check predicate on the "tenant" field. It's identical to TenantEQ.
func Tenant(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTenant, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// Nickname applies equality check predicate on the "nickname" field. It's identical to NicknameEQ.
func Nickname(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldNickname, v))
}

// CompanyUUID applies equality check predicate on the "company_uuid" field. It's identical to CompanyUUIDEQ.
func CompanyUUID(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCompanyUUID, v))
}

// OidcURL applies equality check predicate on the "oidc_url" field. It's identical to OidcURLEQ.
func OidcURL(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOidcURL, v))
}

// TenantEQ applies the EQ predicate on the "tenant" field.
func TenantEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTenant, v))
}

// TenantNEQ applies the NEQ predicate on the "tenant" field.
func TenantNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTenant, v))
}

// TenantIn applies the In predicate on the "tenant" field.
func TenantIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldTenant, vs...))
}

// TenantNotIn applies the NotIn predicate on the "tenant" field.
func TenantNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTenant, vs...))
}

// TenantGT applies the GT predicate on the "tenant" field.
func TenantGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldTenant, v))
}

// TenantGTE applies the GTE predicate on the "tenant" field.
func TenantGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTenant, v))
}

// TenantLT applies the LT predicate on the "tenant" field.
func TenantLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldTenant, v))
}

// TenantLTE applies the LTE predicate on the "tenant" field.
func TenantLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTenant, v))
}

// TenantContains applies the Contains predicate on the "tenant" field.
func TenantContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldTenant, v))
}

// TenantHasPrefix applies the HasPrefix predicate on the "tenant" field.
func TenantHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldTenant, v))
}

// TenantHasSuffix applies the HasSuffix predicate on the "tenant" field.
func TenantHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldTenant, v))
}

// TenantEqualFold applies the EqualFold predicate on the "tenant" field.
func TenantEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldTenant, v))
}

// TenantContainsFold applies the ContainsFold predicate on the "tenant" field.
func TenantContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldTenant, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldName, v))
}

// NicknameEQ applies the EQ predicate on the "nickname" field.
func NicknameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldNickname, v))
}

// NicknameNEQ applies the NEQ predicate on the "nickname" field.
func NicknameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldNickname, v))
}

// NicknameIn applies the In predicate on the "nickname" field.
func NicknameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldNickname, vs...))
}

// NicknameNotIn applies the NotIn predicate on the "nickname" field.
func NicknameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldNickname, vs...))
}

// NicknameGT applies the GT predicate on the "nickname" field.
func NicknameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldNickname, v))
}

// NicknameGTE applies the GTE predicate on the "nickname" field.
func NicknameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldNickname, v))
}

// NicknameLT applies the LT predicate on the "nickname" field.
func NicknameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldNickname, v))
}

// NicknameLTE applies the LTE predicate on the "nickname" field.
func NicknameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldNickname, v))
}

// NicknameContains applies the Contains predicate on the "nickname" field.
func NicknameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldNickname, v))
}

// NicknameHasPrefix applies the HasPrefix predicate on the "nickname" field.
func NicknameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldNickname, v))
}

// NicknameHasSuffix applies the HasSuffix predicate on the "nickname" field.
func NicknameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldNickname, v))
}

// NicknameIsNil applies the IsNil predicate on the "nickname" field.
func NicknameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldNickname))
}

// NicknameNotNil applies the NotNil predicate on the "nickname" field.
func NicknameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldNickname))
}

// NicknameEqualFold applies the EqualFold predicate on the "nickname" field.
func NicknameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldNickname, v))
}

// NicknameContainsFold applies the ContainsFold predicate on the "nickname" field.
func NicknameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldNickname, v))
}

// CompanyUUIDEQ applies the EQ predicate on the "company_uuid" field.
func CompanyUUIDEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCompanyUUID, v))
}

// CompanyUUIDNEQ applies the NEQ predicate on the "company_uuid" field.
func CompanyUUIDNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCompanyUUID, v))
}

// CompanyUUIDIn applies the In predicate on the "company_uuid" field.
func CompanyUUIDIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldCompanyUUID, vs...))
}

// CompanyUUIDNotIn applies the NotIn predicate on the "company_uuid" field.
func CompanyUUIDNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCompanyUUID, vs...))
}

// OidcURLEQ applies the EQ predicate on the "oidc_url" field.
func OidcURLEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOidcURL, v))
}

// OidcURLNEQ applies the NEQ predicate on the "oidc_url" field.
func OidcURLNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldOidcURL, v))
}

// OidcURLIn applies the In predicate on the "oidc_url" field.
func OidcURLIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldOidcURL, vs...))
}

// OidcURLNotIn applies the NotIn predicate on the "oidc_url" field.
func OidcURLNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldOidcURL, vs...))
}

// OidcURLGT applies the GT predicate on the "oidc_url" field.
func OidcURLGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldOidcURL, v))
}

// OidcURLGTE applies the GTE predicate on the "oidc_url" field.
func OidcURLGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldOidcURL, v))
}

// OidcURLLT applies the LT predicate on the "oidc_url" field.
func OidcURLLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldOidcURL, v))
}

// OidcURLLTE applies the LTE predicate on the "oidc_url" field.
func OidcURLLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldOidcURL, v))
}

// OidcURLContains applies the Contains predicate on the "oidc_url" field.
func OidcURLContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldOidcURL, v))
}

// OidcURLHasPrefix applies the HasPrefix predicate on the "oidc_url" field.
func OidcURLHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldOidcURL, v))
}

// OidcURLHasSuffix applies the HasSuffix predicate on the "oidc_url" field.
func OidcURLHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldOidcURL, v))
}

// OidcURLEqualFold applies the EqualFold predicate on the "oidc_url" field.
func OidcURLEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldOidcURL, v))
}

// OidcURLContainsFold applies the ContainsFold predicate on the "oidc_url" field.
func OidcURLContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldOidcURL, v))
}

// HasCompany applies the HasEdge predicate on the "company" edge.
func HasCompany() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CompanyTable, CompanyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCompanyWith applies the HasEdge predicate on the "company" edge with a given conditions (other predicates).
func HasCompanyWith(preds ...predicate.Company) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newCompanyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
